version: "3.6"

services:
  main:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    command: bash -x /run.sh
    volumes:
      - ./.ssh:/root/.ssh
      - ./run.sh:/run.sh
    environment:
      GIT_USERNAME: "tooruuetani"
      GIT_EMAIL: "tooruuetani@mgw.ryoden.co.jp"
      BUCKET: "Ryoden/scoop-bucket"
